apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cma-openshift-demo-servicemonitor
  namespace: cma
  labels:
    release: prometheus  # must match your Prometheus Operator label
spec:
  selector:
    matchLabels:
      app: cma-openshift-demo
  namespaceSelector:
    matchNames:
      - cma
  endpoints:
    - port: 8080-tcp
      path: /actuator/prometheus
      interval: 15s